replicaCount: 1

image:
  repository: bkuslapur/helm-sample
  tag: v1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: false
  host: myapp.local

resources: {}