apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: rbac-demo
spec:
  serviceAccountName: demo-sa
  containers:
  - name: kubectl
    image: bitnami/kubectl
    command: ["sleep", "3600"]